title: Private 1.17.1 Survival Server
logo: /assets/img/logo.png
description: Simple website to show basic info regarding my minecraft server.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
